### ISSUE TITLE
Loader not displaying on adding multiple loaders

### ISSUE THREAD

**Issue by nileshpol18** [ANSCoder/ANLoader#2]
I am calling three APIs, synchronously. Also, before making each api call, I am adding ANLoader without removing previous one, because I have to remove it after all three calls completed.

However, I get following message in debugger and loader stops animating before all service calls are completed.

Error: Loadering already active now, please stop that before creating a new one.

(It should stop animating only after we hide it, not on adding multiple loaders)

**Comment by ANSCoder** [comment]
@nileshpol18  Hello  this - "Error: Loading already active now, please stop that before creating a new one." is not error we are avoiding here another instance for  Loading view every time you need to make hide `ANLoader.hide()` by calling this function otherwise you can do once thing before calling multiple API call load loading single time only then stop end of the all sync task done. 

This is for safety purpose I have done because you need to call hide methods multiple times that's why I have given this.

I hope this will help you. If you having any issue again let me know.

**Comment by narasimhanallamsetty** [comment]
Hi, I have installed ANLoader using cocoa pods. But it is giving errors. Can you tell me from where I can download latest framework? I'm using Xcode 10.0.
